apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "espresso-shop-web.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app:  {{- include "espresso-shop-web.selectorLabels" . | nindent 6 }}
